### ISSUE TITLE
IDB file cannot be opened

### ISSUE THREAD

**Issue by Mewgood** [CyberThreatAlliance/cryptowall_v3#2]
The IDB file cannot be opened in IDA 6.8, although the pdf report on CryptoWall 3.0 states that it was created in IDA 6.8.

If I just open the file, IDA will say that it is not a valid database. If I rename the file to id0, IDA will ask if it should try to repair it; if you say yes to this, it will throw an error:
bTree error: bad B-tree header

**Comment by jgrunzweig** [comment]
Corrected in latest commit
